# # Force Controller -----------------------------------
# gazebo_ros_control:
#    pid_gains:
#      j2n7_mod_joint_1: {p: 1.0, i: 0.01, d: 0.0}
#      j2n7_mod_joint_2: {p: 1.0, i: 0.01, d: 0.0}
#      j2n7_mod_joint_3: {p: 1.0, i: 0.01, d: 0.0}
#      j2n7_mod_joint_4: {p: 1.0, i: 0.01, d: 0.0}
#      j2n7_mod_joint_5: {p: 3.0, i: 0.01, d: 0.0}
#      j2n7_mod_joint_6: {p: 3.0, i: 0.01, d: 0.0}
#      j2n7_mod_joint_7: {p: 10.0, i: 0.01, d: 0.0}


j2n7_mod:

  impedance_controller:
    type: force_controllers/impedance_controller
    joints: [j2n7_mod_joint_1,j2n7_mod_joint_2,j2n7_mod_joint_3,j2n7_mod_joint_4,j2n7_mod_joint_5,j2n7_mod_joint_6,j2n7_mod_joint_7]
    ft_sensor:
      - ft_sensor
    robot_description: /robot_description
    # Select the control Type Among:
    # - classical: Classical Impedance Control
    # - variable: Slippage Variable Impedance Control
    # - Gravity: Gravity Compensation
    # - PD: PD Controller
    control_type: classical
    # Select the desired control space
    # - Cartesian: Cartesian space control
    # - Joint: Joint space control
    control_space: cartesian
    
    # Gains of the Controller
    # Joint Space Control gains
    # Cartesian COntrol Gains
    gains:
      joints:
        Md: [1.0,1.0,1.0,1.0,1.0,1.0,0.5]
        Dd: [1.05,1.05,1.05,1.05,1.05,1.05,1.05]
        Kd: [600.0,600.0,600.0,600.0,3000.0,3000.0,5000.0]
      cartesian:
        Md: [1.0,1.0,1.0,1.0,1.0,1.0]
        Dd: [0.05,0.05,0.05,0.05,0.05,0.05]
        Kd: [6.0,10.0,1.0,1.0,1.0,1.0]
        Wq: [6.0,6.0,6.0,6.0,30.0,30.0,50.0]
    trajectory:
      A: [0.0,0.00,0.0]
      omega: [0.0,0.0,0.0]
    joint_limits:
      lower: [rad(-2*pi), rad(30/180*pi) , rad(-5*pi/4),  rad(30/180*pi) ,rad(-2*pi), rad(-2*pi), rad(-2*pi)]
      upper: [rad(2*pi),  rad(330/180*pi), rad(pi/4),  rad(330/180*pi)   ,rad(2*pi),  rad(2*pi),  rad(2*pi)]
      activation_percentage: 0.2
      max_damping_gains: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]


  admittance_controller:
    type: force_controllers/admittance_controller
    joints: [j2n7_mod_joint_1,j2n7_mod_joint_2,j2n7_mod_joint_3,j2n7_mod_joint_4,j2n7_mod_joint_5,j2n7_mod_joint_6,j2n7_mod_joint_7]
    ft_sensor:
      - ft_sensor
    robot_description: /robot_description
    # Select the control Type Among:
    # - classical: Classical Admittance Control
    # - variable: Slippage Variable Admittance Control
    # - Gravity: Gravity Compensation
    # - PD: PD Controller
    control_type: classical
    # Select the desired control space
    # - Cartesian: Cartesian space control
    # - Joint: Joint space control
    control_space: cartesian
    
    # Gains of the Controller
    # Joint Space Control gains
    # Cartesian COntrol Gains
    gains:
      joints:
        Md: [1.0,1.0,1.0,1.0,1.0,1.0,0.5]
        Dd: [1.05,1.05,1.05,1.05,1.05,1.05,1.05]
        Kd: [600.0,600.0,600.0,600.0,3000.0,3000.0,5000.0]
      cartesian:
        Md: [1.0,1.0,1.0,1.0,1.0,1.0]
        Dd: [0.05,0.05,0.05,0.05,0.05,0.05]
        Kd: [6.0,10.0,1.0,1.0,1.0,1.0]
        Wq: [6.0,6.0,6.0,6.0,30.0,30.0,50.0]
    trajectory:
      A: [0.0,0.00,0.0]
      omega: [0.0,0.0,0.0]
    joint_limits:
      lower: [rad(-2*pi), rad(30/180*pi) , rad(-5*pi/4),  rad(30/180*pi) ,rad(-2*pi), rad(-2*pi), rad(-2*pi)]
      upper: [rad(2*pi),  rad(330/180*pi), rad(pi/4),  rad(330/180*pi)   ,rad(2*pi),  rad(2*pi),  rad(2*pi)]
      activation_percentage: 0.2
      max_damping_gains: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
